### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by terrifricker**
This is from the GitHub CODE_OF_CONDUCT for small communities.  I've added one of my email addresses to be used for complaints.

### CODE REVIEW

**Comment by terrifricker** [comment]
This document doesn't need to be added at this time, so our repository is more casual.

**Comment by ArchitectFromMars** [comment]
Reopening this original PR. Everyone should see it, I'll see if I can add everybody into the Reviewers name. Let's approve it, and merge it. It needs to be part of every collaboration, no matter the size or scope of the project.

**Review by ArchitectFromMars — APPROVED** [review]
looks good to me

**Review by juancwu — APPROVED** [review]
👌👍👏

**Pull request merged**
