### PR TITLE
Added fonts 'Roboto' and 'Lato'

### PR DESCRIPTION
**Pull request by juancwu**
To use/apply the fonts into any html page, we just need to add a `<link>` in `<head>...</head>`.

Example:

```html
<head>
    <link rel="stylesheet" href="/css/fonts.css">
</head>
```

PS: It looks like I changed a lot in the files, but its my auto-formatter(prettier). The content are the same. I just added a `<link>` to add the fonts.

### CODE REVIEW

**Comment by terrifricker** [comment]
> To use/apply the fonts into any html page, we just need to add a `<link>` in `<head>...</head>`.
> 
> Example:
> 
> ```
> <head>
>     <link rel="stylesheet" href="/css/fonts.css">
> </head>
> ```

Question.  Is the first slash in front of css needed?  Is it a different location from css/fonts.css?  Or does it really refer to the same place?  I'm actually not sure.

**Comment by juancwu** [comment]
> > To use/apply the fonts into any html page, we just need to add a `<link>` in `<head>...</head>`.
> > Example:
> > ```
> > <head>
> >     <link rel="stylesheet" href="/css/fonts.css">
> > </head>
> > ```
> 
> Question. Is the first slash in front of css needed? Is it a different location from css/fonts.css? Or does it really refer to the same place? I'm actually not sure.

I added the slash because now the html file is inside the pages folder. Without the slash it will look for a relative path. With the slash it will look in our root directory.

**Comment by terrifricker** [comment]
Perfect.  Thanks!

**Review by terrifricker — APPROVED** [review]
Approved.  Thank you for organizing files.  I use prettifier, too.

**Pull request merged**
