### PR TITLE
Added solar system template

### PR DESCRIPTION
**Pull request by juancwu**
Please checkout the solar system design in your local repository. Leave behind any comments/suggestions to make it better. For now it is just a simple template to have a rough idea of what we want at the end.

These are the space icons we could use as a fallback when 3D is not supported.
v0019

Any suggestion for the background color?

### CODE REVIEW

**Review by terrifricker — APPROVED** [review]
I like it @juancwu , and the icons are great, too.

Note: it changed the formatting of index.html, but I don't think we should worry about that until we have  contributing standards.

**Comment by juancwu** [comment]
> I like it @juancwu , and the icons are great, too.
> 
> Note: it changed the formatting of index.html, but I don't think we should worry about that until we have contributing standards.

Yes, I changed index.html to have a way to navigate to solar-system.html. We can change the way we get there later on the line.

**Comment by ArchitectFromMars** [comment]
The fallback icons are a great idea. For background color, I like that deep purple color, almost black but not quite.

**Comment by ArchitectFromMars** [comment]
approved

**Pull request merged**
