### PR TITLE
Icons rollback

### PR DESCRIPTION
**Pull request by ArchitectFromMars**
hey Terri! :tada: I "Photoshopped" the icons for the **rollback**. Merge if you like 'em.

[See all icons here](https://www.screencast.com/t/LLklx2aiQ)

### CODE REVIEW

**Comment by juancwu** [comment]
Great job! I see that code of conduct is also is this pull request, which is great. Was there a problem getting the icons in svg format? SVG is just more scalable and lighter, but can work around this if svg is not possible.

**Comment by ArchitectFromMars** [comment]
> Great job! I see that code of conduct is also is this pull request, which is great. Was there a problem getting the icons in svg format? SVG is just more scalable and lighter, but can work around this if svg is not possible.

Oh-no... the Code of Conduct, that's a mistake. I forgot to include it in the _.gitignore_ file. I'm not finished with that.
I don't know how to generate svg format, yet. I made them png, and I know the file size is bigger compared to svg. I will work on that tomorrow 📌

**Review by terrifricker — APPROVED** [review]
Thank you for removing your code of conduct article.

**Comment by juancwu** [comment]
> > Great job! I see that code of conduct is also is this pull request, which is great. Was there a problem getting the icons in svg format? SVG is just more scalable and lighter, but can work around this if svg is not possible.
> 
> Oh-no... the Code of Conduct, that's a mistake. I'm not finished with that and had no intention to share it yet. It's actually [listed in my gitIgnore file](https://www.screencast.com/t/4rGucIuma0TZ) and somehow it was still committed to the push.
> 
> I don't know how to generate svg format, yet. I made them png, and I know the file size is bigger compared to svg. I will work on that tomorrow 📌

No problem. There is no need to rush in doing that. We can work with png files and they are a fallback, so hopefully they are not going to be used very often. Generating 3D models is the hard part and the heaviest part.

**Pull request merged**
